### PR TITLE
patch: signature display redesign

### PR DESCRIPTION
**Pull request by Andreea-Lupu**
**What type of PR is this?**

**Which issue does this PR fix**:

**What does this PR do / Why do we need it**:

**If an issue # is not available please add repro steps and logs from IPAMD/CNI showing the issue**:

**Testing done on this change**:

**Automation added to e2e**:

**Will this break upgrades or downgrades. Has updating a running cluster been tested?**:

**Does this change require updates to the CNI daemonset config files to work?**:

**Does this PR introduce any user-facing change?**:

```release-note

```

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by andaaron** [comment]
Attaching some issues with aligning the icons.

Tag_details_Cosign_icon_not_alligned_with_CVE_icon
Repo_list_tile_unsigned_icon_not_alligned_with_CVE_icon

As a separate note I had the same signature type icon is shown multiple times if there are multiple signatures available. Is this intended?

**Comment by andaaron** [comment]
multiple_signatures_repo_details

**Comment by rchincha** [comment]
Make it a single icon
"Authors" -> "Signed-by: [list of authors]"

**Comment by andaaron** [comment]
Conclusion is to show a single icon per signing tool

**Review by raulkele — APPROVED** [review]

**Review by andaaron — APPROVED** [review]

**Comment by andaaron** [comment]
@Andreea-Lupu, @raulkele, thank you again for this feature!

**Pull request merged**
