### PR TITLE
chore: fix dependabot alerts

### PR DESCRIPTION
**Pull request by rchincha**
**What type of PR is this?**

**Which issue does this PR fix**:

**What does this PR do / Why do we need it**:

**If an issue # is not available please add repro steps and logs from IPAMD/CNI showing the issue**:

**Testing done on this change**:

**Automation added to e2e**:

**Will this break upgrades or downgrades. Has updating a running cluster been tested?**:

**Does this change require updates to the CNI daemonset config files to work?**:

**Does this PR introduce any user-facing change?**:

```release-note

```

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by rchincha** [comment]
@raulkele if you are still up for it, can u pls see if you can move this along? think I am close.

**Comment by rchincha** [comment]
@raulkele can u give some feedback on the ci failure?

**Comment by rchincha** [comment]
@andaaron tested this with zot build, and works fine. We just need to fix the unit tests.
Let's first bump up react-dom (this PR) to 18.x and then let's look at 19.x
We use quite a few libs and they need to catch up too.

**Comment by raulkele** [comment]
Im in the process of checking the issues

**Comment by raulkele** [comment]
I believe I've found the issue, been fiddling around with it for a while. #367 is finally starting to bite us. It's getting more and more difficult to upgrade our dependencies while using the outdated toolchain. I'll see if I can get these to pass while I investigate a bit about the toolchain upgrade during Christmas vacation

**Comment by rchincha** [comment]
> I believe I've found the issue, been fiddling around with it for a while. #367 is finally starting to bite us. It's getting more and more difficult to upgrade our dependencies while using the outdated toolchain. I'll see if I can get these to pass while I investigate a bit about the toolchain upgrade during Christmas vacation

I tested zot itself against this change. UI renders fine and nothing obvious seems broken.

**Comment by raulkele** [comment]
> > I believe I've found the issue, been fiddling around with it for a while. #367 is finally starting to bite us. It's getting more and more difficult to upgrade our dependencies while using the outdated toolchain. I'll see if I can get these to pass while I investigate a bit about the toolchain upgrade during Christmas vacation
> 
> I tested zot itself against this change. UI renders fine and nothing obvious seems broken.
> 
> Was trying to fix the following, without success :(
> 
> ```
> console.error
>       Warning: An update to ForwardRef(TouchRipple) inside a test was not wrapped in act(...).
>       
>       When testing, code that causes React state updates should be wrapped into act(...):
> ```

Yup, the mismatch between newer dependencies and old toolchain is causing tests to mees up. I tested the ui myself and found no issue. It's up to you if you wanna give me a couple of days to make it pass the checks or if we need to merge it as is

**Comment by rchincha** [comment]
> It's up to you if you wanna give me a couple of days to make it pass the checks or if we need to merge it as is

I can wait :) and help appreciated.

**Comment by rchincha** [comment]
https://www.npmjs.com/package/react-dom
^ not sure if rest of the ecosystem is ready for 19.x just yet

**Comment by raulkele** [comment]
Opened a draft PR #466  based on your changes here with some unittest fixes and some additional package updates that weren't vulnerable but to be up to date with the other changes.
Got the unit tests fixed but I seem to be having some sort of trivy related error in the test data population script for the e2e tests.

I can open a PR to your branch here @rchincha, or clean up mine if we wanna drop this in favor of that one. Your call

**Comment by rchincha** [comment]
> Opened a draft PR #466 based on your changes here with some unittest fixes and some additional package updates that weren't vulnerable but to be up to date with the other changes. Got the unit tests fixed but I seem to be having some sort of trivy related error in the test data population script for the e2e tests.
> 
> I can open a PR to your branch here @rchincha, or clean up mine if we wanna drop this in favor of that one. Your call

Let's continue building on PR #466 

@andaaron can you pls help with the 'trivy' image failure in e2e test in that PR?

**Comment by andaaron** [comment]
> @andaaron can you pls help with the 'trivy' image failure in e2e test in that PR?

Fixed in https://github.com/project-zot/zui/pull/467

**Comment by raulkele** [comment]
Cleaned and updated #466

**Comment by rchincha** [comment]
Superseded by PR #466

**Pull request closed without merging**
